# Jykell configuration
#markdown: redcarpet
#highlighter: pygments
markdown: kramdown
kramdown:
  input: GFM
highlighter: none
paginate: 5
language: 'en-uk'

# Website info
name: 'Strongbrew: Angular and RxJS blog'
description: ""

url: https://blog.strongbrew.io
short_url: 'blog.strongbrew.io'
disqus_brecht: brechtbilliet
disqus_kwinten: kwintenpghostio
# edit baseurl to simply '/' if using as your personal page (instead of a project page)
baseurl: /
url: https://blog.strongbrew.io/

# Permalinks
permalink: /:title/
# permalink: /author/:username
# permalink: /tag/:tag

# gems and other configs
plugins: [jekyll-paginate, jekyll-prism-plugin]
exclude: [vendor]

# Additional settings available on the front-matter
# Site logo in the index.html (as in demo.ghost.io)
# Author's page cover in _layouts/author.html
# The same for page.html and tag.html layouts
# Post's page cover as a per-post basis _posts/...
# Disqus comments as a per-post basis
# ...


# Settings for builing master branch with travis-ci
# with jekyll-travis


# Settings for deploy rake task
# Username and repo of Github repo, e.g.
# https://github.com/USERNAME/REPO.git
# username defaults to ENV['GIT_NAME'] used by Travis
# repo defaults to USERNAME.github.io
# Branch defaults to "source" for USERNAME.github.io
# or "master" otherwise
safe: false
lsi: false
username: strongbrewio
repo: strongbrewio.github.io
branch: develop
relative_source: ./
destination: ../jasper-pages/
production_url:  https://strongbrewio.github.io/
source_url:  https://github.com/strongbrewio/strongbrewio.github.io/

exclude:
  - README.md
  - Rakefile
  - Gemfile
  - Gemfile.lock
  - changelog.md
  - "*.Rmd"
  - vendor
  - .travis.yml
